config/routes.rb
Rails.application.routes.draw do
  get "messages", to: "messages#home", as: "messages"
  post "messages", to: "messages#create"
  post "connect", to: "messages#connect", as: "connect"
  post "add/form", to: "messages#add", as: "add_form"
  post "messages/:id", to: "messages#show", as: "show_messages"
  resources :leaderboards, only: [:index]
  resources :rooms
  post "rooms/new", to: "rooms#create", as: "start_room"
  post "rooms/:id/concede", to: "rooms#concede", as: "concede"
  get 'tictactoe', to: "tictactoe#new", as: "tictactoe"
  get 'login', to: "sessions#new", as: "login_form"
  post 'login', to: "sessions#create", as: "login"
  delete 'logout', to: "sessions#destroy", as: "logout"
  root 'welcome#index'
  get "rooms/:id/history/:turn", to: "rooms#history", as: "history"
  resources :users
  get "/home", to: "users#home", as: "home"
  get "tictactoe/info", to: "tictactoe#info", as: "tictactoe_info"
  get "/about", to: "welcome#about", as: "about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :from, class_name: "User"
  belongs_to :to, class_name: "User"
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ApplicationHelper
  def home
    @user = get_user
    options1 = {to: @user}
    options2 = {from: @user}
    if session[:from]
      @from = User.find(session[:from])
      options1[:from] = @from
      options2[:to] = @from
    end
    @messages = Message.where(options1).or(Message.where(options2)).reject(&:title).sort_by(&:created_at).reverse
    @conversations = Message.where(to: @user).map(&:from)
    @conversations += Message.where(from: @user).map(&:to)
    @conversations.uniq!
    @others = User.all - @conversations
    render layout: "messages"
  end

  def new
  end

  def add
    flash[:add_conversation] = true
    redirect_to messages_path
  end

  def connect
    Message.create(from: get_user, to_id: params[:to_id], title: "connection")
    session[:from] = params[:to_id]
    redirect_to messages_path
  end

  def create
    @message = Message.create(attr)
    if @message.valid?
      add_message "Your message was successfuly sent"
    else
      add_error @message.errors.full_messages
    end
    to = User.find(params[:message][:to_id])
    if to.ai
      text = ChatBot.new.talk
      Message.create(to_id: params[:message][:from_id], from: to, text: text)
    end
    redirect_to messages_path
  end

  def show
    from = User.find(params[:id])
    session[:from] = from.id
    redirect_to messages_path
  end

  private
  def attr
    params.require(:message).permit(:title, :text, :from_id, :to_id)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/home.html.erb
<div class="messages_page">
  <div><%= flash[:messages] if flash[:messages]%></div>
    <div class="users">
        <h1><b>Conversations</b></h1>
        <% @conversations.each do |user| %>
            <p class="pr-img-l"><%= image_tag(user.avatar.variant(resize: "50x50!")) if user.avatar.attached? %></p>
            <p><%= link_to user.username, show_messages_path(user), method: :post %></p>
        <%end%>
        <% if flash[:add_conversation] %>
          <%= form_tag connect_path do %>
            <%= select_tag :to_id, options_from_collection_for_select(@others, :id, :username)%>
            <%= submit_tag "Converse"%>
          <% end %>
        <% else %>
          <%= link_to "+", add_form_path, method: :post %>
        <% end%>


        </div>
        <div class="messages">
  <% if @from %>
        <h3><b><%= link_to @from.username, user_path(@from) %></b></h3>
  <% end %>
<div class="messages_form">
  <% if @from %>
    <%= form_for Message.new do |f|%>

    <p>
      <%= f.text_area :text%>
    </p>
    <p>
      <%= f.hidden_field :from_id, value: @user.id%>
    </p>
    <p>
      <%= f.hidden_field :to_id, value: @from.id%>
    </p>
    <p id="messages_send">
      <%= f.submit "Send message"%>
    </p>
    <% end %>
  <% end %>
</div>

<div class="message_inner">
  <div class="from">
    <% if @from %>
      <% @messages.each do |message| %>
        <div class="from-message">
          <% if message.from == @user %>
            <%= message.title %>
            <%= message.text %>
            <p id="message_time">sent at <%= message.created_at.strftime("%T"+" on "+"%d %m %Y")%></p>
          <%end%>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="to">
    <% if @from %>
      <% @messages.each do |message| %>
        <div class="to-message">
         <% if message.from != @user %>
          <%= message.title %>
          <%= message.text %>
          <p id="message_time">sent at <%= message.created_at.strftime("%T"+" on "+"%d %m %Y")%></p>
          <%end%>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

  </div>
</div>