config/routes.rb
Rails.application.routes.draw do
  get "messages", to: "messages#home", as: "messages"
  post "messages", to: "messages#create"
  post "connect", to: "messages#connect", as: "connect"
  post "add/form", to: "messages#add", as: "add_form"
  post "messages/:id", to: "messages#show", as: "show_messages"
  resources :leaderboards, only: [:index]
  resources :rooms
  post "rooms/new", to: "rooms#create", as: "start_room"
  post "rooms/:id/concede", to: "rooms#concede", as: "concede"
  get 'tictactoe', to: "tictactoe#new", as: "tictactoe"
  get 'login', to: "sessions#new", as: "login_form"
  post 'login', to: "sessions#create", as: "login"
  delete 'logout', to: "sessions#destroy", as: "logout"
  root 'welcome#index'
  get "rooms/:id/history/:turn", to: "rooms#history", as: "history"
  resources :users
  get "/home", to: "users#home", as: "home"
  get "tictactoe/info", to: "tictactoe#info", as: "tictactoe_info"
  get "/about", to: "welcome#about", as: "about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_side_menu.html.erb
<nav role="navigation">
  <div id="menuToggle">
    <input type="checkbox" />
    <span><a class="fas fa-gamepad" id=gamepad></a></span>
    <ul id="menu">
      <%= link_to "<li>Home</li>".html_safe, home_path%>
      <%= link_to "<li>Personal Settings</li>".html_safe, edit_user_path(curr_user) %>
      <%= link_to "<li>Messages</li>".html_safe, messages_path %>
      <%= link_to "<li>Leaderboard</li>".html_safe, leaderboards_path%>
      <%= link_to "<li>Previous Games</li>".html_safe, rooms_path%>
      <%= link_to "<li>Info</li>".html_safe, tictactoe_info_path%>
      <%= link_to "<li>About</li>".html_safe, about_path%>
      <%=link_to("<li>Log out</li>".html_safe, logout_path, method: :delete) %>


    </ul>
  </div>
</nav>