config/routes.rb
Rails.application.routes.draw do
  get "messages", to: "messages#home", as: "messages"
  post "messages", to: "messages#create"
  post "connect", to: "messages#connect", as: "connect"
  post "add/form", to: "messages#add", as: "add_form"
  post "messages/:id", to: "messages#show", as: "show_messages"
  resources :leaderboards, only: [:index]
  resources :rooms
  post "rooms/new", to: "rooms#create", as: "start_room"
  post "rooms/:id/concede", to: "rooms#concede", as: "concede"
  get 'tictactoe', to: "tictactoe#new", as: "tictactoe"
  get 'login', to: "sessions#new", as: "login_form"
  post 'login', to: "sessions#create", as: "login"
  delete 'logout', to: "sessions#destroy", as: "logout"
  root 'welcome#index'
  get "rooms/:id/history/:turn", to: "rooms#history", as: "history"
  resources :users
  get "/home", to: "users#home", as: "home"
  get "tictactoe/info", to: "tictactoe#info", as: "tictactoe_info"
  get "/about", to: "welcome#about", as: "about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :check_id
  def index
    return redirect_to home_path if curr_user
  end

  def about
    render layout: "application"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>About</h1>

<h2>
  A mod 2 project at Flatiron School that finally connects lonely souls.
</h2>

<h3>
  Here are two people who made this project
</h3>

<div class="container">
  <div id="card-1">
		<div class="card-about">
      <div class="card-header">
        <img class="photo" src="https://avatars3.githubusercontent.com/u/44968477?s=400&v=4" alt="Alisher Zakir" style="width:50%">
        <h1 class="card-title">Alisher Zakir</h1>
      </div>
      <div class="card-body">
          <p class="card-content">What is 9 till 5? I code 24/7!</p>
      </div>
      <div class="card-footer">
        <a href="https://github.com/AlisherZakir" title="GitHub" class="card-button">GitHub</a>
      </div>
    </div>
  </div>

  <div id="card-2">
		<div class="card-about">
		  <div class="card-header">
        <img class="photo" src="https://avatars0.githubusercontent.com/u/45695723?s=400&v=4" alt="Vlad Georgiev" style="width:50%">
			  <h1 class="card-title">Vlad Georgiev</h1>
		  </div>
		<div class="card-body">
			<p class="card-content">Let me code that!</p>
		</div>
    <div class="card-footer">
	    <a href="https://github.com/VladTGeorgiev" title="GitHub" class="card-button">GitHub</a>
		</div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="title">
  <h1>
    <span>W</span>
    <span>e</span>
    <span>l</span>
    <span>c</span>
    <span>o</span>
    <span>m</span>
    <span>e</span>
    <span>!</span>
  </h1>
</div>

<div class="neon">
<div class= "w-wrapper">
  <div class="wrapper">
    <h1><%= link_to "Sign Up", new_user_path %></h1>
  </div>
</div>
  <br>
<div>
  <div class="wrapper">
    <h1><%= link_to "Log In", login_form_path %></h1>
  </div>
</div>
</div>