config/routes.rb
Rails.application.routes.draw do
  get "messages", to: "messages#home", as: "messages"
  post "messages", to: "messages#create"
  post "connect", to: "messages#connect", as: "connect"
  post "add/form", to: "messages#add", as: "add_form"
  post "messages/:id", to: "messages#show", as: "show_messages"
  resources :leaderboards, only: [:index]
  resources :rooms
  post "rooms/new", to: "rooms#create", as: "start_room"
  post "rooms/:id/concede", to: "rooms#concede", as: "concede"
  get 'tictactoe', to: "tictactoe#new", as: "tictactoe"
  get 'login', to: "sessions#new", as: "login_form"
  post 'login', to: "sessions#create", as: "login"
  delete 'logout', to: "sessions#destroy", as: "logout"
  root 'welcome#index'
  get "rooms/:id/history/:turn", to: "rooms#history", as: "history"
  resources :users
  get "/home", to: "users#home", as: "home"
  get "tictactoe/info", to: "tictactoe#info", as: "tictactoe_info"
  get "/about", to: "welcome#about", as: "about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tictactoe.rb
class Tictactoe < ApplicationRecord
  belongs_to :room
  serialize :boxes, Array
  serialize :history, Array

  def game_at(turn)
    self.history = history
    return nil if turn > history.length - 1 || turn  < -history.length

    arr = []

    history[0..turn].each do |move|
      player, box = move.split(",")
      arr[box.to_i] = player
    end
    arr
  end


  def next_turn(params)
    arr = self.boxes.dup
    new_history = self.history.dup
    params.each do |i, player|
      arr[i.to_i] = player
      new_history << "#{player},#{i}"
    end
    update(boxes: arr, history: new_history)
  end

  def next_player
    player = (self.player + 1) % 2
    update(player: player)
  end

  def over?
    return true if self.status != "active"
    return update(status: "#{self.player}") if won?
    return update(status: "draw") if draw?
    false
  end

  def draw?
    self.boxes.size == 9 && self.boxes.none?(&:nil?)
  end

  def won?
    i = self.player.to_s
    boxes = self.boxes
    arr = []
    arr.<<(boxes[0] == i && boxes[0] == boxes[1] && boxes[0] == boxes[2])
       .<<(boxes[0] == i && boxes[0] == boxes[3] && boxes[0] == boxes[6])
       .<<(boxes[0] == i && boxes[0] == boxes[4] && boxes[0] == boxes[8])
       .<<(boxes[1] == i && boxes[1] == boxes[4] && boxes[1] == boxes[7])
       .<<(boxes[2] == i && boxes[2] == boxes[4] && boxes[2] == boxes[6])
       .<<(boxes[2] == i && boxes[2] == boxes[5] && boxes[2] == boxes[8])
       .<<(boxes[3] == i && boxes[3] == boxes[4] && boxes[3] == boxes[5])
       .<<(boxes[6] == i && boxes[6] == boxes[7] && boxes[6] == boxes[8])

    arr.any?
  end

end

app/controllers/tictactoe_controller.rb
class TictactoeController < ApplicationController
  def new
    @game = Tictactoe.new
  end
  def info
    render layout: "application"
  end
end

app/helpers/tictactoe_helper.rb
module TictactoeHelper
end

app/views/tictactoe/_box.html.erb
<% player = (curr_user == @room.host.username ?  0 : 1)%>


<%= check_box_tag "game[boxes][#{num}]", player, !!box, disabled: (!!box || !@your_turn), class: "player#{box}"%>

app/views/tictactoe/new.html.erb
<h1>Tic Tac Toe</h1>

<div id="messages_field">
  <div id="messages">
    <div id="play_again">
      <%= link_to("Concede", concede_path(@room), method: :post) if @active%>
      <%= link_to "Play Again?", new_room_path if flash[:again]%>

    </div>
    <div id="status"><h2><%= flash[:message] if flash[:message]%></h2></div>
    <div id="return_home">
      <%= link_to "Exit", home_path if flash[:again]%>
      <%= form_tag room_path(@room), method: :patch do%>
        <%= submit_tag "End Turn", disabled: !@your_turn if @active && @your_turn%>
    </div>
  </div>
</div>
<% if flash[:errors]%>
  <% flash[:errors].each do |error|%>
    <h3><%= error %></h3>
  <% end %>
<% end %>

<h2><%= "Waiting for the other player, please refresh" unless (@your_turn || !@active)%></h2>

<div class="game">
  <div class="board">

      <% (0..8).each do |n| %>
        <%= "<br>".html_safe if n > 0 && n % 3 == 0%>
        <%= render partial: "tictactoe/box", locals: {num: n, box: @boxes[n]}%>
      <% end %>
  </div>
</div>
<% end %>